
[server]
headless = true
enableCORS = false
enableWebsocketCompression = false
enableXsrfProtection = false
maxUploadSize = 200
port = 5000
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[logger]
level = "error"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
magicEnabled = true
installDependencies = true
